apiVersion: apps/v1
kind: Deployment
metadata:
  name: hangman-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hangman
  template:
    metadata:
      labels:
        app: hangman
    spec:
      containers:
      - name: hangman-app
        image: hangman-game:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hangman-service
spec:
  selector:
    app: hangman
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort