pipeline {
    agent {
        docker { 
            image 'mcr.microsoft.com/dotnet/sdk:9.0'
            // This line sets working folders and cache in an accessible area
            args '-u root -e DOTNET_CLI_HOME=/tmp -e DOTNET_NOLOGO=1'
        }
    }
    environment {
        // Setting the solution path
        SOLUTION_PATH = 'HangmanByTudor/HangmanByTudor.sln'
    }
    stages {
        stage('Build') { 
            steps {
                echo 'Compiling...'
                sh "dotnet build ${SOLUTION_PATH} --configuration Release"
            }
        }
        stage('Test') { 
            steps {
                sh "dotnet test ${SOLUTION_PATH} --configuration Release --no-build --logger 'trx;LogFileName=test-results.trx'"
                // Adaug? aceast? linie pentru a schimba permisiunile fi?ierului
                sh "chmod 644 **/test-results.trx" 
            }
        }
    }
    post {
        always {
            // Archiving test results to see them in Jenkins UI
            mstest testResultsFile: '**/test-results.trx', keepLongStdio: true
        }
        failure {
            echo 'Build or tests failed. Check logs!'
        }
    }
}