pipeline {
    agent {
        docker { 
            image 'mcr.microsoft.com/dotnet/sdk:9.0' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'dotnet build'
            }
        }
        stage('Test') { 
            steps {
                sh 'dotnet test'
            }
        }
    }
}