pipeline {
    agent any

    environment {
        SOLUTION_PATH = 'HangmanByTudor/HangmanByTudor.sln'
        DOTNET_ROOT = '/opt/dotnet'
        PATH = "${env.PATH}:/opt/dotnet:/opt/dotnet/tools"
    }

    stages {
        stage('Build & Test') { 
            steps {
                echo 'Compiling...'
                sh "dotnet build ${SOLUTION_PATH} --configuration Release"
                echo 'Running automated tests...'
                sh "dotnet test ${SOLUTION_PATH} --configuration Release --no-build --logger 'junit;LogFilePath=test-results.xml'"
            }
        }
        
        stage('Docker Build') { 
            steps {
                script {
                    sh 'docker build -f HangmanByTudor/Dockerfile -t hangman-game:latest .'
                    // save the image in a local file
                    sh 'docker save hangman-game:latest > hangman-game.tar'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    sh 'docker load < hangman-game.tar'
            
                    withEnv(['KUBECONFIG=/home/vboxuser/.kube/config']) {
                        sh 'kubectl apply -f k8s-deployment.yaml'
                        sh 'kubectl rollout status deployment/hangman-deployment'
                    }
                }
            }
        }
    }
    
    post {
        always {
            junit '**/test-results.xml'
        }
        failure {
            echo 'Build or tests failed. Check logs!'
        }
    }
}